### ISSUE TITLE
How to prepare Dataset？QAQ

### ISSUE THREAD

**Issue by Baizx98** [zhiqi-0/PaGraph#1]
Hi，I am new to GNN，I wanna run your PaGraph but I encountered a problem when preparing the dataset.So could you write a detailed README for Prepare Dataset

**Comment by YijianLiu** [comment]
> Hi，I am new to GNN，I wanna run your PaGraph but I encountered a problem when preparing the dataset.So could you write a detailed README for Prepare Dataset

hey, have you solved the problem
